name = "Mathy"
uuid = "7af93308-22a2-11e9-0f14-799dfe8cab44"
authors = ["Takafumi Arakaki <aka.tkf@gmail.com>"]
version = "0.1.0"

[deps]
Transducers = "28d57a85-8fef-5791-bfe6-a80928e7c999"

[compat]
Transducers = "0.2.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
